name: umami_tracker
description: A Umami tracker for Flutter.
version: 0.1.0
homepage: https://davidserrano.io

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  devicelocale: ^0.5.2
  dio: ^4.0.6
  fk_user_agent: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter: